-- =====================================================================
-- MIGRAÇÃO — Mural de postagens das ONGs (curtidas e comentários)
-- Rodar no SQL Editor do Supabase, depois da MIGRACAO.sql anterior.
-- =====================================================================

BEGIN;

-- Postagens: só ONGs publicam (ong_id referencia a própria ONG).
CREATE TABLE posts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ong_id      BIGINT NOT NULL REFERENCES ongs(id) ON DELETE CASCADE,
    conteudo    TEXT NOT NULL,
    imagem      TEXT,
    criado_em   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_posts_ong ON posts(ong_id);
CREATE INDEX idx_posts_criado_em ON posts(criado_em DESC);

-- Curtidas: um usuário (doador ou ong) curte um post no máximo uma vez.
CREATE TABLE post_curtidas (
    post_id     BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    usuario_id  BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    criado_em   TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (post_id, usuario_id)
);

-- Comentários: qualquer usuário autenticado pode comentar.
CREATE TABLE post_comentarios (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id     BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    usuario_id  BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    conteudo    TEXT NOT NULL,
    criado_em   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_comentarios_post ON post_comentarios(post_id);

COMMIT;

-- Lembrete: como o app usa a chave anon do Supabase direto no navegador,
-- confira se as políticas de RLS dessas 3 tabelas permitem select/insert
-- (e delete em post_curtidas, para o "descurtir") para usuários autenticados,
-- do mesmo jeito que já deve estar configurado para as tabelas existentes.
